# Generated by Django 2.2.1 on 2019-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('hash', models.TextField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='articles/')),
            ],
            options={
                'db_table': 'image_tb',
            },
        ),
    ]
