# Generated by Django 2.2.1 on 2019-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImage', '0002_auto_20190516_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModelAnother',
            fields=[
                ('hash', models.TextField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='articles/')),
            ],
            options={
                'db_table': 'image_bt',
            },
        ),
    ]
