# Generated by Django 2.2.1 on 2019-05-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImage', '0003_imagemodelanother'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModelAnother',
        ),
        migrations.AlterModelTable(
            name='imagemodel',
            table='image_bt',
        ),
    ]
